### ISSUE TITLE
Multiple composer.json using extra bower, have the same when the packages will be an error

### ISSUE THREAD

**Issue by ForeverGlory** [php-kit/composer-bower-plugin#1]
Multiple composer.json using extra bower, have the same when the packages will be an error.
For example,
When a package require "jquery": "latest", also relies on another package, execution `composer update`  will be an error, file bower.json dependencies "jquery": "latest latest"

**Comment by claudio-silva** [comment]
Hi,
We're using this plugin on several complex projects with many interdependent packages, and we're having no issues.
Are  you using the "latest" keyword as a version number?
If so, that is a unsupported configuration. I wasn't even aware you could do that, and I'm not sure you can do that.
Either use specific version numbers, ex: `^2.0.3`or `2.*`, or use `*` to mean "any" (i.e. the latest) version.
If I'm missing the point, could you provide a simple example that makes it clear and that I can easily test?

**Comment by ForeverGlory** [comment]
my project composer.json
```ymal
{
    "require": {
        "foreverglory/web-bundle": "dev-master",
        "foreverglory/admin-bundle": "dev-master"
    }
}
```
foreverglory/web-bundle composer.json
```ymal
{
    "require": {
        "php-kit/composer-bower-plugin": "~1.0"
    },
    "extra": {
        "bower": {
            "require": {
                "jquery": "~2.0",
                "jquery.ui": "latest",
                "bootstrap": "latest",
                "fontawesome": "latest"
            }
        }
    }
}
```
foreverglory/admin-bundle composer.json
```yaml
{
    "require": {
        "php-kit/composer-bower-plugin": "~1.0"
    },
    "extra": {
        "bower": {
            "require": {
                "jquery": "~2.0",
                "jquery.ui": "latest",
                "bootstrap": "latest",
                "fontawesome": "latest",
                "adminlte": "~2.3"
            }
        }
    }
}
```
if only require `foreverglory/web-bundle` package, bower is no problem. but, require more package, bower install failed.
